# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\ManagementInvoice\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1137, 486)
        MainWindow.setStyleSheet("font-size: 18px")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 521, 421))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/ManagementInvoice/assets/images/Invoice.png"))
        self.label.setObjectName("label")
        self.groupBoxLogin = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxLogin.setGeometry(QtCore.QRect(560, 10, 561, 421))
        self.groupBoxLogin.setObjectName("groupBoxLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBoxLogin)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.label_2.setObjectName("label_2")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.groupBoxLogin)
        self.lineEditUsername.setGeometry(QtCore.QRect(180, 60, 341, 41))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBoxLogin)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.label_3.setObjectName("label_3")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBoxLogin)
        self.lineEditPassword.setGeometry(QtCore.QRect(180, 140, 341, 41))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.checkBoxSaveInformation = QtWidgets.QCheckBox(parent=self.groupBoxLogin)
        self.checkBoxSaveInformation.setGeometry(QtCore.QRect(180, 200, 171, 31))
        self.checkBoxSaveInformation.setObjectName("checkBoxSaveInformation")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.groupBoxLogin)
        self.pushButtonLogin.setGeometry(QtCore.QRect(180, 260, 161, 41))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1137, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxLogin.setTitle(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.checkBoxSaveInformation.setText(_translate("MainWindow", "Save Information"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
