# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\ShopGroceries\ui\home\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 948)
        MainWindow.setStyleSheet("font-size: 16px")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 100, 741, 771))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\KTLT_UEL\\ShopGroceries\\ui\\home\\ShopGroceries/assets/images/shop.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 581, 51))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 27))
        self.menubar.setObjectName("menubar")
        self.menuProducts = QtWidgets.QMenu(parent=self.menubar)
        self.menuProducts.setObjectName("menuProducts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProducts = QtGui.QAction(parent=MainWindow)
        self.actionProducts.setObjectName("actionProducts")
        self.actionCatalog = QtGui.QAction(parent=MainWindow)
        self.actionCatalog.setObjectName("actionCatalog")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuProducts.addAction(self.actionProducts)
        self.menuProducts.addAction(self.actionCatalog)
        self.menuProducts.addAction(self.actionExit)
        self.menubar.addAction(self.menuProducts.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Welcome to my Store</span></p></body></html>"))
        self.menuProducts.setTitle(_translate("MainWindow", "Settings"))
        self.actionProducts.setText(_translate("MainWindow", "Products"))
        self.actionCatalog.setText(_translate("MainWindow", "Catalog"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
