# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\File_exercise\Bai1\ui\FractionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 455)
        MainWindow.setStyleSheet("font-size: 16px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 781, 341))
        self.groupBox.setStyleSheet("font-size: 16px")
        self.groupBox.setObjectName("groupBox")
        self.textEditFraction = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEditFraction.setGeometry(QtCore.QRect(30, 40, 441, 271))
        self.textEditFraction.setObjectName("textEditFraction")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSave.setGeometry(QtCore.QRect(560, 40, 141, 61))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonRead = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonRead.setGeometry(QtCore.QRect(560, 130, 141, 61))
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(560, 220, 141, 61))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 241, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Fraction"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save "))
        self.pushButtonRead.setText(_translate("MainWindow", "Read"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Fraction with File</span></p></body></html>"))
