# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\exam\Bai3\ui\SignupWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 448)
        MainWindow.setStyleSheet("font-size: 18px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 0, 121, 21))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 711, 331))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 71, 31))
        self.label_2.setObjectName("label_2")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(120, 40, 551, 41))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 91, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdiUsername = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdiUsername.setGeometry(QtCore.QRect(120, 110, 351, 41))
        self.lineEdiUsername.setObjectName("lineEdiUsername")
        self.pushButtonSuggestUsername = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSuggestUsername.setGeometry(QtCore.QRect(510, 110, 141, 41))
        self.pushButtonSuggestUsername.setObjectName("pushButtonSuggestUsername")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 91, 31))
        self.label_4.setObjectName("label_4")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPassword.setGeometry(QtCore.QRect(120, 180, 351, 41))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonRegister.setGeometry(QtCore.QRect(270, 260, 151, 41))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.pushButtonSuggestPassword = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSuggestPassword.setGeometry(QtCore.QRect(510, 180, 141, 41))
        self.pushButtonSuggestPassword.setObjectName("pushButtonSuggestPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Authentication"))
        self.groupBox.setTitle(_translate("MainWindow", " Sign Up"))
        self.label_2.setText(_translate("MainWindow", "Email: "))
        self.label_3.setText(_translate("MainWindow", "Username: "))
        self.pushButtonSuggestUsername.setText(_translate("MainWindow", "Suggest"))
        self.label_4.setText(_translate("MainWindow", "Password: "))
        self.pushButtonRegister.setText(_translate("MainWindow", "Register"))
        self.pushButtonSuggestPassword.setText(_translate("MainWindow", "Suggest"))
