# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\ManagementInvoice\ui\MainWindow\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 708)
        MainWindow.setStyleSheet("font-size: 18px")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 741, 441))
        self.groupBox.setObjectName("groupBox")
        self.tableWidgetListInvoice = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidgetListInvoice.setGeometry(QtCore.QRect(20, 30, 701, 391))
        self.tableWidgetListInvoice.setObjectName("tableWidgetListInvoice")
        self.tableWidgetListInvoice.setColumnCount(4)
        self.tableWidgetListInvoice.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListInvoice.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListInvoice.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListInvoice.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListInvoice.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 171, 41))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 520, 741, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonCreate = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonCreate.setGeometry(QtCore.QRect(20, 50, 131, 41))
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(210, 50, 131, 41))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.pushButtonShowDetail = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonShowDetail.setGeometry(QtCore.QRect(400, 50, 131, 41))
        self.pushButtonShowDetail.setObjectName("pushButtonShowDetail")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonDelete.setGeometry(QtCore.QRect(590, 50, 131, 41))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "List Invoice"))
        item = self.tableWidgetListInvoice.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "InvoiceID"))
        item = self.tableWidgetListInvoice.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidgetListInvoice.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SendTo"))
        item = self.tableWidgetListInvoice.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ReceivedFrom"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">List Invoice</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Feature"))
        self.pushButtonCreate.setText(_translate("MainWindow", "Create"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButtonShowDetail.setText(_translate("MainWindow", "Show Detail"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
