# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\exam\Bai1\ui\FractionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 639)
        MainWindow.setStyleSheet("font-size: 16px")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 0, 321, 31))
        self.label.setObjectName("label")
        self.textEditFraction = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditFraction.setGeometry(QtCore.QRect(30, 60, 541, 461))
        self.textEditFraction.setObjectName("textEditFraction")
        self.lineEditResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditResult.setGeometry(QtCore.QRect(30, 540, 341, 41))
        self.lineEditResult.setObjectName("lineEditResult")
        self.pushButtonCreate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCreate.setGeometry(QtCore.QRect(610, 60, 171, 51))
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.pushButtonDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDisplay.setGeometry(QtCore.QRect(610, 130, 171, 51))
        self.pushButtonDisplay.setObjectName("pushButtonDisplay")
        self.pushButtonSum = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSum.setGeometry(QtCore.QRect(610, 200, 171, 51))
        self.pushButtonSum.setObjectName("pushButtonSum")
        self.pushButtonMaxFraction = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMaxFraction.setGeometry(QtCore.QRect(610, 270, 171, 51))
        self.pushButtonMaxFraction.setObjectName("pushButtonMaxFraction")
        self.pushButtonSortAscending = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSortAscending.setGeometry(QtCore.QRect(610, 340, 171, 51))
        self.pushButtonSortAscending.setObjectName("pushButtonSortAscending")
        self.pushButtonSortDescending = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSortDescending.setGeometry(QtCore.QRect(610, 410, 171, 51))
        self.pushButtonSortDescending.setObjectName("pushButtonSortDescending")
        self.pushButtonClearAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClearAll.setGeometry(QtCore.QRect(610, 480, 171, 51))
        self.pushButtonClearAll.setObjectName("pushButtonClearAll")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Operation Fraction</span></p><p><br/></p></body></html>"))
        self.pushButtonCreate.setText(_translate("MainWindow", "Create 100 fractions"))
        self.pushButtonDisplay.setText(_translate("MainWindow", "Display"))
        self.pushButtonSum.setText(_translate("MainWindow", "Sum"))
        self.pushButtonMaxFraction.setText(_translate("MainWindow", "Max Fraction"))
        self.pushButtonSortAscending.setText(_translate("MainWindow", "Sort ascending"))
        self.pushButtonSortDescending.setText(_translate("MainWindow", "Sort descending"))
        self.pushButtonClearAll.setText(_translate("MainWindow", "Clear All"))
