# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\KTLT_UEL\List_exercise_1\list_fraction\ui\FractionMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 356)
        MainWindow.setStyleSheet("font-size: 16px; ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 761, 201))
        self.groupBox.setObjectName("groupBox")
        self.textEditSum = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEditSum.setGeometry(QtCore.QRect(260, 20, 411, 151))
        self.textEditSum.setObjectName("textEditSum")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 20, 101, 41))
        self.label.setObjectName("label")
        self.pushButtonSum = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSum.setGeometry(QtCore.QRect(50, 80, 141, 41))
        self.pushButtonSum.setObjectName("pushButtonSum")
        self.lineEditResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditResult.setGeometry(QtCore.QRect(280, 250, 231, 41))
        self.lineEditResult.setObjectName("lineEditResult")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 131, 31))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Enter data"))
        self.label.setText(_translate("MainWindow", "List Fraction: "))
        self.pushButtonSum.setText(_translate("MainWindow", "Sum"))
        self.label_2.setText(_translate("MainWindow", "Result: "))
